name: easy_onvif
version: 3.1.1+4
homepage: https://github.com/faithoflifedev/packacges/easy_onvif
description: This package can work with a variety of ONVIF compatible devices allowing for IP Cameras and NVRs (network video recorders) to be integrated into Dart and Flutter applications.
repository: https://github.com/faithoflifedev/easy_onvif_workspace

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5
  dio: ^5.7.0
  ffi: ^2.1.3
  html_unescape: ^2.0.0
  http: ^1.2.2
  http_parser: ^4.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  path: ^1.9.0
  uuid: ^4.5.1
  xml: ^6.5.0
  xml2json: ^6.2.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^5.0.0
  publish_tools: ^1.0.0+5
  test: ^1.25.8
