name: easy_onvif
version: 3.1.1+6
homepage: https://github.com/faithoflifedev/packacges/easy_onvif
description: This package can work with a variety of ONVIF compatible devices allowing for IP Cameras and NVRs (network video recorders) to be integrated into Dart and Flutter applications.
repository: https://github.com/faithoflifedev/easy_onvif_workspace

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5
  dio: ^5.8.0+1
  ffi: ^2.1.4
  html_unescape: ^2.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  path: ^1.9.0
  uuid: ^4.5.1
  xml: ^6.5.0
  xml2json: ^6.2.6
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^5.1.1
  publish_tools: ^1.0.0+5
  test: ^1.25.15
