name: examples
version: 0.0.1
homepage: https://github.com/faithoflifedev/easy_onvif_workspace
description: An example
repository: https://github.com/faithoflifedev/easy_onvif_workspace/packages/easy_onvif/example

publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  easy_onvif:
    path: ../
  http: ^1.2.0
  dio: ^5.4.0
  loggy: ^2.0.3
  universal_io: ^2.2.2
  yaml: ^3.1.2
