name: flutter_model
description: A new Flutter project to test Onvif.

publish_to: "none"

version: 1.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  easy_onvif:
    path: ../../
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  flutter_loggy: ^2.0.2
  flutter_solidart: ^1.7.0
  getwidget: ^4.0.0
  http: ^1.2.1
  loggy: ^2.0.3
  path: ^1.9.0
  shared_preferences: ^2.2.2
  universal_io: ^2.2.2
  yaml: ^3.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  solidart_lint: ^1.1.2

dependency_overrides:
  collection: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.yaml
    - assets/discovery.dll
